on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: ["14.x", "16.x", "18.x", "20.x"]
    steps:
      - uses: "actions/checkout@v3"
      - name: "Use node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: "${{ matrix.node-version }}"
      - name: "Build static website"
        run: npm build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            output
