on:
  push:
    branches:
      - "main"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Set up node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.x"
      - name: "Build static website"
        run: npm run build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r site.zip site
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            site.zip
